switched back to false due to build error
           throw new TypeError("Failed to parse URL from " + input, { cause: err });
                  ^
TypeError: Failed to parse URL from /api/project
    at new Request (node:internal/deps/undici/undici:7134:19)
    at r (/vercel/path0/.next/server/chunks/982.js:9376:65)
    ... 2 lines matching cause stack trace ...
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:405:5)
      at new URL (node:internal/url:611:13)
      at new Request (node:internal/deps/undici/undici:7132:25)
      at r (/vercel/path0/.next/server/chunks/982.js:9376:65)
      at doOriginalFetch (/vercel/path0/.next/server/chunks/501.js:6216:24)
      at /vercel/path0/.next/server/chunks/501.js:6350:20
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    input: '/api/project',
    code: 'ERR_INVALID_URL'
  }